# Generated by Django 2.2.1 on 2019-07-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location2',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location3',
        ),
    ]
