# Generated by Django 2.2.1 on 2019-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='colour2',
            field=models.CharField(default='please complete country', max_length=50),
        ),
    ]
