# Generated by Django 2.2.3 on 2019-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
    ]
