# Generated by Django 2.2.1 on 2019-07-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_country_colour2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='country',
            name='colour2',
        ),
    ]
