# Generated by Django 2.2.1 on 2019-07-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='add_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country'),
        ),
    ]
