# Generated by Django 2.2.1 on 2019-07-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190711_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add_country',
        ),
    ]
