# Generated by Django 2.2.1 on 2019-07-12 09:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_add_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='found_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='found_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_1',
            field=models.CharField(default='', max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Address 3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_postcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='local_offer_radius',
            field=models.FloatField(default=5, verbose_name='Search radius for local offers (km)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='local_offer_receive',
            field=models.BooleanField(default=False, verbose_name='I would like to receive newsletters with local offers?'),
        ),
    ]
