# Generated by Django 2.2.1 on 2019-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190712_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='local_offer_receive',
            field=models.BooleanField(default=False, verbose_name='I would like to receive newsletters with local offers'),
        ),
    ]
