# Generated by Django 2.2.1 on 2019-07-12 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190712_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lon',
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
