# Generated by Django 2.2.1 on 2019-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_temp_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
