# Generated by Django 2.2.1 on 2019-07-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_temp2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temp2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temp_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temp_location',
        ),
    ]
