# Generated by Django 2.2.3 on 2019-07-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190714_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country'),
        ),
    ]
