# Generated by Django 2.2.3 on 2019-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190717_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='run_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
