# Generated by Django 2.2.3 on 2019-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190730_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='local_offer_radius',
            field=models.FloatField(blank=True, default=5, verbose_name='Search radius for local offers (km)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='local_offer_receive',
            field=models.BooleanField(default=False, verbose_name='I would like to receive the weekly local offers newsletter'),
        ),
    ]
