# Generated by Django 2.2.3 on 2019-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190802_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='found_address_valid',
            field=models.BooleanField(default=False),
        ),
    ]
