# Generated by Django 2.2.3 on 2019-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_found_address_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='found_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Confirmed address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='found_address_valid',
            field=models.BooleanField(default=False, verbose_name='Valid address'),
        ),
    ]
