# Generated by Django 2.2.3 on 2019-08-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190803_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='found_address_valid',
        ),
    ]
