# Generated by Django 2.2.3 on 2019-08-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_profile_found_address_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country'},
        ),
    ]
