# Generated by Django 2.2.3 on 2019-08-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190803_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country', verbose_name='Country'),
        ),
    ]
