# Generated by Django 2.2.3 on 2019-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190803_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch')], default='EN', max_length=2, verbose_name='Newsletter Language'),
        ),
    ]
