# Generated by Django 2.2.3 on 2019-07-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0019_auto_20190717_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('recipient_count', models.PositiveIntegerField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country')),
            ],
        ),
    ]
