# Generated by Django 2.2.3 on 2019-08-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country'),
        ),
    ]
