# Generated by Django 2.2 on 2019-05-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotRecommended', models.BooleanField(default=False)),
                ('InitialOvenTimeMins', models.IntegerField(default=0)),
                ('InitialOvenTempC', models.IntegerField(default=0)),
                ('OvenTempC', models.IntegerField(default=0)),
                ('InternalTempC', models.IntegerField(default=0)),
                ('MinsPerKg', models.IntegerField(default=0)),
                ('MinsFixed', models.IntegerField(default=0)),
                ('RestTimeMins', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CookingInfo',
                'ordering': ['MeatType', 'CookingLevel__CookingLevelSort'],
            },
        ),
        migrations.CreateModel(
            name='CookingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CookingLevel', models.CharField(max_length=30)),
                ('CookingLevelSort', models.IntegerField()),
            ],
            options={
                'ordering': ['CookingLevelSort'],
            },
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeatTypeName', models.CharField(max_length=60)),
                ('PortionKGPerAdult', models.FloatField(default=0)),
                ('PortionKGPerChild', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['MeatTypeName'],
            },
        ),
        migrations.CreateModel(
            name='CookingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default=0)),
                ('PlanName', models.CharField(blank=True, max_length=300)),
                ('InitialOvenTempC', models.IntegerField(default=0)),
                ('OvenTempC', models.IntegerField(default=0)),
                ('InternalTempC', models.IntegerField(default=0)),
                ('InitialOvenTimeMins', models.IntegerField(default=0)),
                ('MinsPerKg', models.IntegerField(default=0)),
                ('MinsFixed', models.IntegerField(default=0)),
                ('AdultsCount', models.IntegerField(default=0)),
                ('ChildrenCount', models.IntegerField(default=0)),
                ('MealSizeScaling', models.IntegerField(default=1)),
                ('EatingTime', models.TimeField(blank=True)),
                ('CookingTime', models.TimeField(blank=True)),
                ('CookingStart', models.TimeField(blank=True)),
                ('RecordCreated', models.DateTimeField(auto_now_add=True)),
                ('RecordModified', models.DateTimeField(auto_now=True)),
                ('CookingLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.CookingLevel')),
                ('MeatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.MeatType')),
            ],
        ),
        migrations.AddField(
            model_name='cookinglevel',
            name='CookingInfo',
            field=models.ManyToManyField(through='AppTimesCalc.CookingInfo', to='AppTimesCalc.MeatType'),
        ),
        migrations.AddField(
            model_name='cookinginfo',
            name='CookingLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.CookingLevel'),
        ),
        migrations.AddField(
            model_name='cookinginfo',
            name='MeatType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.MeatType'),
        ),
        migrations.AddConstraint(
            model_name='cookinginfo',
            constraint=models.UniqueConstraint(fields=('MeatType', 'CookingLevel'), name='UniquePerMeat'),
        ),
    ]
