# Generated by Django 2.2.3 on 2019-08-02 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotRecommended', models.BooleanField(default=False)),
                ('BrowningMins', models.IntegerField(default=0)),
                ('BrowningTempC', models.IntegerField(default=0)),
                ('OvenTempC', models.IntegerField(default=0)),
                ('InternalTempC', models.IntegerField(default=0)),
                ('MinsPerKg', models.IntegerField(default=0)),
                ('MinsFixed', models.IntegerField(default=0)),
                ('RestTimeMins', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CookingInfo',
                'ordering': ['MeatType', 'CookingLevel__CookingLevelSort'],
            },
        ),
        migrations.CreateModel(
            name='CookingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CookingLevel', models.CharField(max_length=30, unique=True)),
                ('CookingLevel_en', models.CharField(max_length=30, null=True, unique=True)),
                ('CookingLevel_de', models.CharField(max_length=30, null=True, unique=True)),
                ('CookingLevelSort', models.IntegerField()),
            ],
            options={
                'ordering': ['CookingLevelSort'],
            },
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeatTypeName', models.CharField(max_length=60, unique=True)),
                ('MeatTypeName_en', models.CharField(max_length=60, null=True, unique=True)),
                ('MeatTypeName_de', models.CharField(max_length=60, null=True, unique=True)),
                ('PortionKGPerAdult', models.FloatField(default=0)),
                ('PortionKGPerChild', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['MeatTypeName'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('PlanDesc', models.TextField(blank=True, verbose_name='Plan Description')),
                ('StartTime', models.TimeField(default=datetime.time(0, 0), verbose_name='Start Time')),
                ('MeatInTime', models.TimeField(default=datetime.time(0, 0), verbose_name='Meat In Time')),
                ('RemoveTime', models.TimeField(default=datetime.time(0, 0), verbose_name='Meat Out Time')),
                ('EatingTime', models.TimeField(default=datetime.time(0, 0), verbose_name='Eating Time')),
                ('WarmupTime', models.DurationField(default=datetime.timedelta(0), verbose_name='Warmup Time')),
                ('CookingTime', models.DurationField(default=datetime.timedelta(0), verbose_name='Cooking Time')),
                ('RestTime', models.DurationField(default=datetime.timedelta(0), verbose_name='Resting Time')),
                ('TotalTime', models.DurationField(default=datetime.timedelta(0), verbose_name='Total Time')),
                ('GivenWeightKg', models.FloatField(default=0.0, verbose_name='Given Weight kg')),
                ('InputWeight', models.CharField(default='', max_length=50, verbose_name='Input Weight')),
                ('OvenTempStandardC', models.IntegerField(default=0, verbose_name='Oven Temperature')),
                ('InternalTempStandardC', models.IntegerField(default=0, verbose_name='Internal Temperature')),
                ('CountAdults', models.IntegerField(default=0, verbose_name='Number of Adults')),
                ('CountChildren', models.IntegerField(default=0, verbose_name='Number of Children')),
                ('CalcType', models.CharField(default='', max_length=20, verbose_name='CalcType')),
                ('RatingStars', models.IntegerField(blank=True, choices=[(0, 'Not rated'), (1, 'One star'), (2, 'Two stars'), (3, 'Three stars')], default=0, null=True, verbose_name='How would you rate our instructions?')),
                ('RatingComment', models.TextField(blank=True, max_length=1000, verbose_name='Tell us how it went...')),
                ('RatingResult', models.IntegerField(blank=True, choices=[(1, 'Very undercooked'), (2, 'Undercooked'), (3, 'Just right'), (4, 'Overcooked'), (5, 'Very overcooked')], default=0, null=True, verbose_name='How well was it cooked compared to what you had in mind?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CookingLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.CookingLevel')),
                ('MeatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.MeatType')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cookinglevel',
            name='CookingInfo',
            field=models.ManyToManyField(through='AppTimesCalc.CookingInfo', to='AppTimesCalc.MeatType'),
        ),
        migrations.AddField(
            model_name='cookinginfo',
            name='CookingLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.CookingLevel'),
        ),
        migrations.AddField(
            model_name='cookinginfo',
            name='MeatType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.MeatType'),
        ),
        migrations.AddConstraint(
            model_name='cookinginfo',
            constraint=models.UniqueConstraint(fields=('MeatType', 'CookingLevel'), name='UniquePerMeat'),
        ),
    ]
