# Generated by Django 2.2 on 2019-06-14 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotRecommended', models.BooleanField(default=False)),
                ('BrowningMins', models.IntegerField(default=0)),
                ('BrowningTempC', models.IntegerField(default=0)),
                ('OvenTempC', models.IntegerField(default=0)),
                ('InternalTempC', models.IntegerField(default=0)),
                ('MinsPerKg', models.IntegerField(default=0)),
                ('MinsFixed', models.IntegerField(default=0)),
                ('RestTimeMins', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CookingInfo',
                'ordering': ['MeatType', 'CookingLevel__CookingLevelSort'],
            },
        ),
        migrations.CreateModel(
            name='CookingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CookingLevel', models.CharField(max_length=30, unique=True)),
                ('CookingLevelSort', models.IntegerField()),
            ],
            options={
                'ordering': ['CookingLevelSort'],
            },
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeatTypeName', models.CharField(max_length=60, unique=True)),
                ('PortionKGPerAdult', models.FloatField(default=0)),
                ('PortionKGPerChild', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['MeatTypeName'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('PlanDesc', models.TextField(blank=True)),
                ('StartTime', models.TimeField(default=datetime.time(0, 0))),
                ('MeatInTime', models.TimeField(default=datetime.time(0, 0))),
                ('RemoveTime', models.TimeField(default=datetime.time(0, 0))),
                ('EatingTime', models.TimeField(default=datetime.time(0, 0))),
                ('WarmupTime', models.DurationField(default=datetime.timedelta(0))),
                ('CookingTime', models.DurationField(default=datetime.timedelta(0))),
                ('RestTime', models.DurationField(default=datetime.timedelta(0))),
                ('TotalTime', models.DurationField(default=datetime.timedelta(0))),
                ('GivenWeightKg', models.FloatField(default=0.0)),
                ('InputWeight', models.CharField(default='', max_length=50)),
                ('OvenTempStandardC', models.IntegerField(default=0)),
                ('InternalTempStandardC', models.IntegerField(default=0)),
                ('CountAdults', models.IntegerField(default=0)),
                ('CountChildren', models.IntegerField(default=0)),
                ('CalcType', models.CharField(default='', max_length=20)),
                ('RatingStars', models.IntegerField(blank=True, choices=[(0, 'Not rated'), (1, 'One star'), (2, 'Two stars'), (3, 'Three stars')], default=0, null=True, verbose_name='How would you rate our instructions?')),
                ('RatingComment', models.TextField(blank=True, max_length=1000, verbose_name='Tell us how it went')),
                ('RatingResult', models.IntegerField(blank=True, choices=[(1, 'Very undercooked'), (2, 'Undercooked'), (3, 'Just right'), (4, 'Overcooked'), (5, 'Very overcooked')], default=0, null=True, verbose_name='How well was it cooked compared to what you had in mind?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CookingLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.CookingLevel')),
                ('MeatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.MeatType')),
            ],
        ),
    ]
