# Generated by Django 2.2.3 on 2019-08-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppTimesCalc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookinglevel',
            name='CookingInfo',
            field=models.ManyToManyField(through='AppTimesCalc.CookingInfo', to='AppTimesCalc.MeatType'),
        ),
        migrations.AddField(
            model_name='cookinginfo',
            name='CookingLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.CookingLevel'),
        ),
        migrations.AddField(
            model_name='cookinginfo',
            name='MeatType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTimesCalc.MeatType'),
        ),
        migrations.AddConstraint(
            model_name='cookinginfo',
            constraint=models.UniqueConstraint(fields=('MeatType', 'CookingLevel'), name='UniquePerMeat'),
        ),
    ]
