# Generated by Django 2.2 on 2019-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTimesCalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meattype',
            options={'ordering': ['MeatTypeName']},
        ),
        migrations.RenameField(
            model_name='meattype',
            old_name='MeatType_Name',
            new_name='MeatTypeName',
        ),
    ]
