# Generated by Django 2.2 on 2019-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTimesCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookinginfo',
            name='RestTimeMins',
            field=models.IntegerField(default=0),
        ),
    ]
