# Generated by Django 2.2.3 on 2019-08-02 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTimesCalc', '0002_auto_20190711_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='CalcType',
            field=models.CharField(default='', max_length=20, verbose_name='CalcType'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='CookingTime',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='CountAdults',
            field=models.IntegerField(default=0, verbose_name='Number of Adults'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='CountChildren',
            field=models.IntegerField(default=0, verbose_name='Number of Children'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='EatingTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Eating Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='GivenWeightKg',
            field=models.FloatField(default=0.0, verbose_name='Given Weight kg'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='InputWeight',
            field=models.CharField(default='', max_length=50, verbose_name='Input Weight'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='InternalTempStandardC',
            field=models.IntegerField(default=0, verbose_name='Internal Temperature'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='MeatInTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Meat In Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='OvenTempStandardC',
            field=models.IntegerField(default=0, verbose_name='Oven Temperature'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='PlanDesc',
            field=models.TextField(blank=True, verbose_name='Plan Description'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='RemoveTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Meat Out Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='RestTime',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Resting Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='StartTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='TotalTime',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total Time'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='WarmupTime',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Warmup Time'),
        ),
    ]
