# Generated by Django 2.2 on 2019-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTimesCalc', '0002_auto_20190614_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='RatingComment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Tell us how it went...'),
        ),
    ]
