# Generated by Django 2.2 on 2019-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTimesCalc', '0002_auto_20190505_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingplan',
            name='MealSizeScaling',
            field=models.IntegerField(default=1),
        ),
    ]
