# Generated by Django 2.2.3 on 2019-08-03 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedEventEditors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default='please complete country', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('comment', models.TextField(blank=True, verbose_name='Event description')),
                ('start_date', models.DateField(verbose_name='Event start date')),
                ('end_date', models.DateField(verbose_name='Event end date')),
                ('includes_offers', models.BooleanField(default=False, verbose_name='Includes offers')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('add_house_number', models.CharField(max_length=100, verbose_name='House Number')),
                ('add_street', models.CharField(max_length=100, verbose_name='Street')),
                ('add_postcode', models.CharField(max_length=100, verbose_name='Postcode')),
                ('add_city', models.CharField(max_length=100, verbose_name='City')),
                ('add_country', models.CharField(max_length=20, verbose_name='Country')),
                ('email', models.EmailField(max_length=254)),
                ('my_address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('opening_hours', models.CharField(max_length=200)),
                ('website', models.TextField(null=True)),
                ('OSM_ID', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('type_text', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('icon_text', models.CharField(max_length=50)),
            ],
        ),
    ]
