# Generated by Django 2.2.1 on 2019-07-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20190701_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='OSM_ID',
            field=models.BigIntegerField(),
        ),
    ]
