# Generated by Django 2.2.1 on 2019-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20190709_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='my_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.TextField(),
        ),
    ]
