# Generated by Django 2.2.1 on 2019-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190701_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='OSM_ID',
            field=models.BigIntegerField(unique=True),
        ),
    ]
