# Generated by Django 2.2.3 on 2019-07-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_auto_20190714_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='add_city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='store',
            name='add_country',
            field=models.CharField(max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='store',
            name='add_house_number',
            field=models.CharField(max_length=100, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='add_postcode',
            field=models.CharField(max_length=100, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='store',
            name='add_street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('comment', models.TextField(verbose_name='Event description')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Event start date and time')),
                ('end', models.DateTimeField(auto_now=True, verbose_name='Event end date and time')),
                ('includes_offers', models.BooleanField(default=False, verbose_name='Includes offers')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorisedEventEditors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='authorised_editors',
            field=models.ManyToManyField(related_name='authorised_editors', through='stores.AuthorisedEventEditors', to=settings.AUTH_USER_MODEL),
        ),
    ]
