# Generated by Django 2.2.1 on 2019-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190709_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
