# Generated by Django 2.2.1 on 2019-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20190701_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='g_search_str',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
