# Generated by Django 2.2.3 on 2019-07-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20190714_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_date',
        ),
    ]
