# Generated by Django 2.2.1 on 2019-07-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_g_search_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='g_search_str',
        ),
    ]
