# Generated by Django 2.2.1 on 2019-07-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_store_g_search_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='add_country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='add_house_number',
            field=models.CharField(max_length=100),
        ),
    ]
