# Generated by Django 2.2.3 on 2019-07-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20190714_2221'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authorisedeventeditors',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='Uniqueperstore'),
        ),
    ]
