# Generated by Django 2.2.1 on 2019-07-06 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20190702_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='store_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
