# Generated by Django 2.2.1 on 2019-07-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20190706_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='long',
            new_name='lon',
        ),
    ]
