# Generated by Django 2.2.3 on 2019-07-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20190717_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='my_name',
        ),
    ]
