# Generated by Django 2.2.1 on 2019-07-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20190706_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='my_address',
        ),
        migrations.AddField(
            model_name='store',
            name='my_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
