# Generated by Django 2.2.1 on 2019-07-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20190708_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default='please complete country', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='my_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.Country'),
        ),
    ]
