# Generated by Django 2.2.3 on 2019-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_name', models.CharField(default='No name given', max_length=100, verbose_name='Recipe name')),
                ('user_comments', models.CharField(max_length=500)),
                ('source_url', models.URLField()),
                ('original_text', models.TextField(verbose_name='Original Recipe')),
                ('converted_text', models.TextField(verbose_name='Converted Recipe')),
                ('conversion_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_source_name', models.CharField(max_length=60, unique=True)),
                ('spoon_type', models.BooleanField(default=False)),
                ('cup_type', models.BooleanField(default=False)),
                ('test_can_delete_add_suffix', models.BooleanField(default=False)),
                ('unit_source_type', models.CharField(choices=[('imp', 'Imperial'), ('met', 'Metric'), ('none', 'None')], max_length=10)),
                ('unit_source_keys', models.CharField(max_length=500)),
                ('unit_dest_name', models.CharField(max_length=60)),
                ('unit_conversion', models.FloatField()),
            ],
        ),
    ]
