# Generated by Django 2.2 on 2019-06-18 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Converters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_source_name', models.CharField(max_length=60, unique=True)),
                ('unit_source_keys', models.CharField(max_length=500)),
                ('unit_dest_name', models.CharField(max_length=60)),
                ('unit_conversion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_name', models.CharField(default='No name given', max_length=100)),
                ('user_comments', models.CharField(max_length=500)),
                ('original_text', models.TextField()),
                ('original_ingredients', models.TextField()),
                ('original_method', models.TextField()),
                ('converted_ingredients', models.TextField()),
                ('converted_method', models.TextField()),
                ('converted_success', models.TextField()),
                ('converted_fails', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
