# Generated by Django 2.2 on 2019-06-18 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecipeConverter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversions',
            new_name='Conversion',
        ),
        migrations.RenameModel(
            old_name='Converters',
            new_name='Converter',
        ),
    ]
