# Generated by Django 2.2 on 2019-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0002_auto_20190618_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='unit_source_type',
            field=models.CharField(choices=[('imp', 'Imperial'), ('met', 'Metric')], default='imp', max_length=10),
        ),
    ]
