# Generated by Django 2.2 on 2019-06-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0003_converter_unit_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='source_url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='converter',
            name='unit_source_type',
            field=models.CharField(choices=[('imp', 'Imperial'), ('met', 'Metric')], max_length=10),
        ),
    ]
