# Generated by Django 2.2.1 on 2019-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0004_auto_20190619_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(default='old record', max_length=50),
            preserve_default=False,
        ),
    ]
