# Generated by Django 2.2.1 on 2019-06-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0005_conversion_conversion_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='converted_ingredients',
            new_name='converted_text',
        ),
    ]
