# Generated by Django 2.2.1 on 2019-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0006_auto_20190621_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='cup_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversion',
            name='spoon_type',
            field=models.BooleanField(default=False),
        ),
    ]
