# Generated by Django 2.2.1 on 2019-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0007_auto_20190621_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='cup_type',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='spoon_type',
        ),
        migrations.AddField(
            model_name='converter',
            name='cup_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='converter',
            name='spoon_type',
            field=models.BooleanField(default=False),
        ),
    ]
