# Generated by Django 2.2.1 on 2019-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0009_auto_20190621_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='add_suffix',
            field=models.BooleanField(default=False),
        ),
    ]
