# Generated by Django 2.2.1 on 2019-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0011_auto_20190623_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='converted_fails',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='converted_method',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='converted_success',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='original_ingredients',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='original_method',
        ),
        migrations.AlterField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(max_length=20),
        ),
    ]
