# Generated by Django 2.2.1 on 2019-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0012_auto_20190625_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_name',
            field=models.CharField(default='No name given', max_length=100, verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='converted_text',
            field=models.TextField(verbose_name='Converted Recipe'),
        ),
    ]
