# Generated by Django 2.2.1 on 2019-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0013_auto_20190626_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(max_length=50),
        ),
    ]
