# Generated by Django 2.2.1 on 2019-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeConverter', '0014_auto_20190626_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='original_text',
            field=models.TextField(verbose_name='Original Recipe'),
        ),
    ]
